// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHRiIOkH2GZTs5RLhIONXsB6vJOveoZk',
    appId: '1:604318905316:web:3d290b43faf06745b20df1',
    messagingSenderId: '604318905316',
    projectId: 'activity13-authentication',
    authDomain: 'activity13-authentication.firebaseapp.com',
    storageBucket: 'activity13-authentication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzHhGibrNmQre7l_90Ie9N4B-DadVklk',
    appId: '1:604318905316:android:62b90ae06cbdd8a0b20df1',
    messagingSenderId: '604318905316',
    projectId: 'activity13-authentication',
    storageBucket: 'activity13-authentication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBXngJykDYM08YNlgayx72Bv8Wnd9ci4',
    appId: '1:604318905316:ios:22a2f6c731aa7291b20df1',
    messagingSenderId: '604318905316',
    projectId: 'activity13-authentication',
    storageBucket: 'activity13-authentication.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBXngJykDYM08YNlgayx72Bv8Wnd9ci4',
    appId: '1:604318905316:ios:22a2f6c731aa7291b20df1',
    messagingSenderId: '604318905316',
    projectId: 'activity13-authentication',
    storageBucket: 'activity13-authentication.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEHRiIOkH2GZTs5RLhIONXsB6vJOveoZk',
    appId: '1:604318905316:web:bbb68a96e31640d9b20df1',
    messagingSenderId: '604318905316',
    projectId: 'activity13-authentication',
    authDomain: 'activity13-authentication.firebaseapp.com',
    storageBucket: 'activity13-authentication.firebasestorage.app',
  );
}
